services:
  php-server:
    build: .
    container_name: php-apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./certs:/etc/apache2/ssl
    working_dir: /var/www/html

  db:
    image: mariadb:10.11
    container_name: mysql-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
