services:
  php-server:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./init.sql:/init.sql
    command: >
      sh -c "
        docker-entrypoint.sh mysqld &
        sleep 10
        mysql -u root -p$DB_PASS $DB_NAME < /init.sql
        wait
      "
